name: Upload Theoretical Computer Science Summary
on:
  push:
    paths:
      - 'semester3/ti/main/**'
jobs:
  upload_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Upload to ComSol
        uses: ./.github/actions/upload-to-comsol
        with:
          file: ./semester3/ti/main/ti-summary.pdf
          access_token: ${{ secrets.TOKEN_TI }}
          url: https://exams.vis.ethz.ch/api/document/jahutz/summary-hs25_0/files/658/update/
