name: Upload Analysis II (by janishutz) Cheat-Sheet
on:
  push:
    paths:
      - 'semester3/analysis-ii/cheat-sheet-jh/**'
jobs:
  upload_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Upload Cheat-Sheet to ComSol
        uses: ./.github/actions/upload-to-comsol
        with:
          access_token: ${{ secrets.TOKEN_ANA_II_JH }}
          file: ./semester3/analysis-ii/cheat-sheet-jh/analysis-ii-cheat-sheet.pdf
          url: https://exams.vis.ethz.ch/api/document/jahutz/analysis-ii-cheatsheet-hs25/files/693/update/
