name: Upload Analysis I (by janishutz) Cheat-Sheet
on:
  push:
    paths:
      - 'semester2/analysis-i/cheat-sheet-jh/**'
jobs:
  upload_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Upload English version to ComSol
        uses: ./.github/actions/upload-to-comsol
        with:
          access_token: ${{ secrets.TOKEN_ANA_I_JH }}
          file: ./semester2/analysis-i/cheat-sheet-jh/cheat-sheet-en.pdf
          url: https://exams.vis.ethz.ch/api/document/jahutz/analysis-i-cheatsheet-fs25/files/654/update/
      - name: Upload German version to ComSol
        uses: ./.github/actions/upload-to-comsol
        with:
          access_token: ${{ secrets.TOKEN_ANA_I_JH }}
          file: ./semester2/analysis-i/cheat-sheet-jh/cheat-sheet-de.pdf
          url: https://exams.vis.ethz.ch/api/document/jahutz/analysis-i-cheatsheet-fs25/files/655/update/
