name: Upload Algorithms and Datastructures Summary
on:
  push:
    paths:
      - 'semester1/algorithms-and-datastructures/**'
jobs:
  build_docs:
    runs_on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Upload to ComSol
        uses: ./.github/actions/upload-to-comsol
        with:
          access_token: {{ secrets.TOKEN_AD }}
          file: ./semester1/algorithms-and-datastructures/ad-janishutz.pdf
          url: https://exams.vis.ethz.ch/api/document/jahutz/summary-hs24_1/files/591/update/
