name: Upload Introduction to Programming Short Summary
on:
  push:
    paths:
      - 'semester1/eprog/**'
jobs:
  upload_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Upload to ComSol
        uses: ./.github/actions/upload-to-comsol
        with:
          access_token: ${{ secrets.TOKEN_EPROG }}
          file: ./semester1/eprog/eprog-janishutz.pdf
          url: https://exams.vis.ethz.ch/api/document/jahutz/short-summary-hs24/files/593/update/
